# This is a basic workflow to help you get started with Actions

name: Tweet Update

# Controls when the workflow will run
on:
  workflow_run:
    workflows: [pages build and deployment]
    types: [completed]

jobs:
  on-success:
      runs-on: ubuntu-latest
      steps:
        - uses: ethomson/send-tweet-action@v1
          with:
            status: "Hi, this is a test!"
            consumer-key: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
            consumer-secret: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
            access-token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
            access-token-secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
